### PR TITLE
refactor: correct absolute paths

### LINKED ISSUE #1: Problematic filepaths
The website has an inconsistent way of writing filepaths, making it quite difficult to potentially contribute to on Linux, as any filepaths starting with a `/`, are automatically interpreted as an absolute path on the vast majority of GNU/Linux systems. 

image
<sub>The first two images load in correctly, the rest does not.</sub>

That means, that if you write `/Images/Badges80x15/{something}`, it tries to find it in the root folder of the system - where all of the core system files are located, because `/` is the core directory. 
Assuming you're on Windows, it's basically like `C://Images/Badges80x15/{something}`. If it were to be written as `Images/Badges80x15/{something}` or  `./Images/Badges80x15/{something}`, it'd find the path correctly on most, if not all, operating systems. 

I'm sure it **could** potentially be an issue if you host it on a dedicated server or something in the future, so it might be better to take care of that ahead of time.

PS. The site is really cool!

### PR DESCRIPTION
**Pull request by onzecki**
Should fix the issue I described in #1 
Please check if it works correctly on your machine, I haven't tested it super thoroughly!

### CODE REVIEW

**Comment by onzecki** [comment]
A bunch of files are broken, mostly in Shrines...
I'll try to convert as many of them to relative paths.

**Comment by onzecki** [comment]
I think ca31c8c22692b43c3cee4d2c88b864d8e54d66d6 fixes everything, I am yet to see something broken on my machine...

**Comment by AstralVRZ** [comment]
Thank you, I will take a look when I get back to my computer.

**Comment by AstralVRZ** [comment]
I appreciate your help, but when I clone your fork and put it on live server in vs code, a lot of pages are completely broken or partially broken. On the partially broken pages it is only the list of links to pages.
firefox_Dc2a40O8FM
firefox_sV3OSEDm11
firefox_9ealToGruq
firefox_SSUIvfiigj
firefox_Q7k4p1qLTV
firefox_zSmWLpVTzQ
firefox_tHZEgr0fE7

**Comment by onzecki** [comment]
Right! Somehow I missed a bunch of index.html's in some of the directories...

**Comment by onzecki** [comment]
as for the partially broken sites, the reason linkList can't find the linkList.html file is because the path is calculated from the point of the html, I think getting the website's root might work by calculating document.location.hostname using js... I'll try it out

**Comment by onzecki** [comment]
Ooops, just realized that the relative filepaths break most js files...

**Comment by onzecki** [comment]
It _should_ work now...
What it basically does, is that whenever a linkList.html is needed, the javascript file goes to the window.location.origin, so https://astralvrz.github.io/ or http://localhost/ and then just appends "linkList.html" to it

if the entire website is to be put into a subdirectory (for example a subdirectory called "meow"), it won't work, as instead of trying to find http://localhost/meow/linkList.html, it will try to find http://localhost/linkList.html
This shouldn't be an issue if hosted on GitHub Pages or whenever hosting it locally...

**Comment by AstralVRZ** [comment]
I think the linkList should just keep using paths like for example `/Contact/` instead of `Contact/` because now if you press on the contact page first and then another page, lets say the about me page, it takes you to `/Contact/About/`. Where as if its `/About/` it goes from the contact page to the about me page normally. 
image

Also the reason the file paths in the 404 page start with a `/` is because the 404 page can appear in any folder, but needs it's css and images from `/css/404.css` and `/Images/Whatever.jpg`.


Next the copyright, and privacy page both in their css need to take the files `/Fonts/pc-9800-bold.ttf` and `/TOS/OrionNebula.jpg` but now when the path is like  this it tries to look for`Fonts/pc-9800-bold.ttf` insde the `Privacy` and `©` folder wich dont exist in there.
image
image

**Comment by onzecki** [comment]
As for the 404 and linkList... I think that it could, yet again, be solved by simply generating the path using javascript, but I suppose it might be alright letting those two pages use links beginning with a /, and just keeping them in mind in case anything goes wrong with those two in the future...

**Comment by AstralVRZ** [comment]
It looks all good now. From now on I will keep in mind relative paths.

**Pull request merged**
